# -*- coding: utf-8 -*-
"""AI_Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mHBZ2EKEQm3qAct608vGAndV58rzQWMF
"""

#VACUUM

room_a = input("Enter status of Room A (dirty/clean): ")
room_b = input("Enter status of Room B (dirty/clean): ")

location = input("Enter vacuum location (A/B): ")

print("\nInitial State:")
print("Room A:", room_a)
print("Room B:", room_b)
print("Vacuum Location:", location)

while room_a == "dirty" or room_b == "dirty":

    if location == "A":

        if room_a == "dirty":
            print("Room A is dirty -> Cleaning Room A")
            room_a = "clean"

        else:
            print("Room A is clean -> Moving to Room B")
            location = "B"

    else:

        if room_b == "dirty":
            print("Room B is dirty -> Cleaning Room B")
            room_b = "clean"

        else:
            print("Room B is clean -> Moving to Room A")
            location = "A"

if room_a == "clean" and room_b == "clean":
    print("\nGoal achieved!")
    print("Both rooms are clean.")

#TICTACTOE

board = [" " for i in range(9)]

while True:

    print(board[0], "|", board[1], "|", board[2])
    print("--+---+--")
    print(board[3], "|", board[4], "|", board[5])
    print("--+---+--")
    print(board[6], "|", board[7], "|", board[8])

    #HUMAN INPUT
    pos = int(input("Enter position (1-9): ")) - 1

    if board[pos] != " ":
        print("Position already occupied!")
        continue

    board[pos] = "X"

    #HUMAN WIN CHECK
    if ((board[0] == board[1] == board[2] == "X") or
        (board[3] == board[4] == board[5] == "X") or
        (board[6] == board[7] == board[8] == "X") or
        (board[0] == board[3] == board[6] == "X") or
        (board[1] == board[4] == board[7] == "X") or
        (board[2] == board[5] == board[8] == "X") or
        (board[0] == board[4] == board[8] == "X") or
        (board[2] == board[4] == board[6] == "X")):

        print("You Win!")
        break

    #DRAW CHECK
    if " " not in board:
        print("Draw!")
        break

    #COMPUTER INPUT
    for i in range(9):
        if board[i] == " ":
            board[i] = "O"
            break

    #COMPUTER WIN CHECK
    if ((board[0] == board[1] == board[2] == "O") or
        (board[3] == board[4] == board[5] == "O") or
        (board[6] == board[7] == board[8] == "O") or
        (board[0] == board[3] == board[6] == "O") or
        (board[1] == board[4] == board[7] == "O") or
        (board[2] == board[5] == board[8] == "O") or
        (board[0] == board[4] == board[8] == "O") or
        (board[2] == board[4] == board[6] == "O")):

        print("Computer Wins!")
        break

    #DRAW CHECK
    if " " not in board:
        print("Draw!")
        break